2. Example 1.

In [2]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = np.flip(arr1d)
print(reversed_arr1d)

[5 4 3 2 1]


In [3]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_rows = np.flip(arr2d, axis=0)
print(reversed_arr2d_rows)

[[4 5 6]
 [1 2 3]]


In [5]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_cols = np.flip(arr2d, axis=1)
print(reversed_arr2d_cols)

[[3 2 1]
 [6 5 4]]


Example 2

In [6]:
arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = arr1d[::-1]
reversed_arr1d

array([5, 4, 3, 2, 1])

In [8]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_rows = arr2d[::-1, :]
reversed_arr2d_rows

array([[4, 5, 6],
       [1, 2, 3]])

In [9]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_cols = arr2d[:, ::-1]
reversed_arr2d_cols

array([[3, 2, 1],
       [6, 5, 4]])

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [11]:
arr = np.array([1, 2, 3, 4])

print(type(arr))
print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [15]:
import numpy as np

matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

result = np.dot(matrix1, matrix2)
result

array([[256.32084621, 252.46312197, 260.87401333, ..., 260.62641504,
        257.58328531, 247.05582501],
       [253.67543087, 244.32891918, 252.24842607, ..., 248.95751475,
        249.34999328, 240.28078106],
       [250.23898368, 236.86589659, 248.3505783 , ..., 247.43106198,
        249.05638891, 244.94223688],
       ...,
       [254.8533519 , 253.75978081, 260.69971753, ..., 257.07860114,
        253.48280962, 247.0872957 ],
       [249.8936328 , 244.72486782, 255.07195357, ..., 248.58107551,
        248.76505272, 243.31405135],
       [259.15308165, 256.3221916 , 263.76276592, ..., 260.38869945,
        255.49783783, 251.30565454]])

In [16]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9]])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.hstack((array1, array2))
print(stacked_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flipping left-right
flipped_lr = np.fliplr(array)
print("Flipped left-right:\n", flipped_lr)

# Flipping up-down
flipped_ud = np.flipud(array)
print("Flipped up-down:\n", flipped_ud)

Flipped left-right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped up-down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
