Question 3

In [1]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = np.flip(arr1d)
print(reversed_arr1d)

[5 4 3 2 1]


In [2]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_rows = np.flip(arr2d, axis=0)
print(reversed_arr2d_rows)

[[4 5 6]
 [1 2 3]]


In [3]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_cols = np.flip(arr2d, axis=1)
print(reversed_arr2d_cols)

[[3 2 1]
 [6 5 4]]


In [4]:
arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = arr1d[::-1]
reversed_arr1d

array([5, 4, 3, 2, 1])

In [5]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_rows = arr2d[::-1, :]
reversed_arr2d_rows

array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
reversed_arr2d_cols = arr2d[:, ::-1]
reversed_arr2d_cols

array([[3, 2, 1],
       [6, 5, 4]])

Question 4

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [8]:
arr = np.array([1, 2, 3, 4])

print(type(arr))
print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int32'>


Question 6

In [9]:
import numpy as np

matrix1 = np.random.rand(1000, 1000)
matrix2 = np.random.rand(1000, 1000)

result = np.dot(matrix1, matrix2)
result

array([[244.8405296 , 253.15428152, 248.07075508, ..., 256.83005103,
        248.40343374, 257.63313797],
       [238.19550554, 237.2792507 , 234.49667917, ..., 253.40345973,
        238.9003963 , 248.88403224],
       [241.76193662, 252.89799246, 244.19548175, ..., 249.54374547,
        241.76903896, 254.9234377 ],
       ...,
       [243.27979827, 246.45630872, 244.42300258, ..., 253.41136807,
        249.76286531, 257.24534955],
       [245.01617201, 243.44884618, 247.57131044, ..., 256.30865627,
        246.43982738, 255.23149239],
       [237.76398982, 247.80270851, 245.85070833, ..., 256.44432951,
        247.46265698, 260.43443526]])

Question 7

In [10]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9]])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stacked_array = np.hstack((array1, array2))
print(stacked_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Question 8

In [12]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Flipping left-right
flipped_lr = np.fliplr(array)
print("Flipped left-right:\n", flipped_lr)

# Flipping up-down
flipped_ud = np.flipud(array)
print("Flipped up-down:\n", flipped_ud)

Flipped left-right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped up-down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Question 9

In [13]:
import numpy as np

array = np.arange(10)

# Split into 3 sub-arrays
sub_arrays = np.array_split(array, 3)

print(sub_arrays)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Question 10

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
c = a + b
print(c)

[5 7 9]


In [15]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([7, 8, 9])

# Broadcasting
c = a + b
print(c)

[[ 8 10 12]
 [11 13 15]]
