1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [1]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, (3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns
interchanged_array = array.T

# Print the interchanged array
print("Interchanged array:")
print(interchanged_array)

Original array:
[[64 74 28]
 [ 7 47 49]
 [64 10 10]]
Interchanged array:
[[64  7 64]
 [74 47 10]
 [28 49 10]]


2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array = np.random.randint(1, 101, 10)

# Print the original array
print("Original array:")
print(array)

# Reshape it into a 2x5 array
array_2x5 = array.reshape(2, 5)

# Print the 2x5 array
print("Reshaped into 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array.reshape(5, 2)

# Print the 5x2 array
print("Reshaped into 5x2 array:")
print(array_5x2)

Original array:
[60 79 30 53 81 91 70 71 24 47]
Reshaped into 2x5 array:
[[60 79 30 53 81]
 [91 70 71 24 47]]
Reshaped into 5x2 array:
[[60 79]
 [30 53]
 [81 91]
 [70 71]
 [24 47]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.rand(4, 4)

# Add a border of zeros around it
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print(bordered_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.26072181 0.49636738 0.40044481 0.84845034 0.        ]
 [0.         0.51775326 0.27016083 0.24198932 0.24445426 0.        ]
 [0.         0.51468738 0.09659273 0.75028961 0.85143913 0.        ]
 [0.         0.1717875  0.52131788 0.82862323 0.70220166 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [8]:
import numpy as np

# Create a NumPy array of strings
strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(strings)
lowercase_arr = np.char.lower(strings)
titlecase_arr = np.char.title(strings)
capitalize_arr = np.char.capitalize(strings)
swapcase_arr = np.char.swapcase(strings)

# Print the results
print("Original Array:       ", strings)
print("Uppercase Array:      ", uppercase_arr)
print("Lowercase Array:      ", lowercase_arr)
print("Title Case Array:     ", titlecase_arr)
print("Capitalize Array:     ", capitalize_arr)
print("Swapcase Array:       ", swapcase_arr)


Original Array:        ['python' 'numpy' 'pandas']
Uppercase Array:       ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array:       ['python' 'numpy' 'pandas']
Title Case Array:      ['Python' 'Numpy' 'Pandas']
Capitalize Array:      ['Python' 'Numpy' 'Pandas']
Swapcase Array:        ['PYTHON' 'NUMPY' 'PANDAS']


6.  Generate a NumPy array of words. Insert a space between each character of every word in the array

In [9]:
import numpy as np

# Define the array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the results
print("Original Array: ", words)
print("Spaced Words Array: ", spaced_words)

Original Array:  ['python' 'numpy' 'pandas']
Spaced Words Array:  ['p y t h o n' 'n u m p y' 'p a n d a s']


7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [10]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [11]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [12]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Define a function to check if a number is prime
def is_prime(n):
    """Return True if n is a prime number, else False."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Find prime numbers in the array
primes = np.array([x for x in random_integers if is_prime(x)])

# Print the results
print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(primes)

Random Integers:
[246 105 795 163  21 515 164 712 718 834  50 390 969 778 102 353 390 765
 619 514 799 607 884 359 635 313 252 449 817  25 447 807 822 571 505 801
 900 852 381 963  38 263 299 597 235 210 449 119 206  96 152  87 620  89
 871 102 966 247 529 332 976 392  22 571 438 607 944  92 850 210 874 394
 744  65 344 960 767 394 525 912 512 885  97 307 759 135 432 441 900 659
 704 497 548 939 997 950 534 104 301 245]

Prime Numbers:
[163 353 619 607 359 313 449 571 263 449  89 571 607  97 307 659 997]


10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages 

In [13]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (assuming 30 days)
daily_temperatures = np.random.randint(60, 90, 30)

# Calculate weekly averages
weekly_averages = []
for week in range(4):
  start_index = week * 7
  end_index = (week + 1) * 7 - 1
  weekly_average = np.mean(daily_temperatures[start_index:end_index + 1])
  weekly_averages.append(weekly_average)

# Print the weekly averages
print("Weekly averages:", weekly_averages)

Weekly averages: [72.0, 73.0, 71.85714285714286, 76.85714285714286]
